

CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY,
    NOME VARCHAR (50) NOT NULL,
    DAT_NASCIMENTO DATETIME,
    DAT_CRIACAO DATETIME,
	DAT_ALTERACAO DATETIME,
	DAT_EXCLUSAO DATETIME,
	CRIADO_POR_USU_ID INT,
	ALTERADO_POR_USU_ID INT,
	EXCLUIDO_POR_USU_ID INT,
    ID_ATIVO INT NOT NULL
)


CREATE TABLE PRODUTOS (
    ID INT PRIMARY KEY,
    NOME VARCHAR (50) NOT NULL,
	VALOR NUMERIC (10,2),
    DAT_CRIACAO DATETIME,
	DAT_ALTERACAO DATETIME,
	DAT_EXCLUSAO DATETIME,
	CRIADO_POR_USU_ID INT,
	ALTERADO_POR_USU_ID INT,
	EXCLUIDO_POR_USU_ID INT,
    ID_ATIVO INT NOT NULL,
)


CREATE SEQUENCE seq_VENDAS 
    AS NUMERIC
	START WITH 1
	INCREMENT BY 1;


CREATE TABLE VENDAS (
    ID INT PRIMARY KEY,
    DAT_CRIACAO DATETIME,
	DAT_ALTERACAO DATETIME,
	DAT_EXCLUSAO DATETIME,
	CRIADO_POR_USU_ID INT,
	ALTERADO_POR_USU_ID INT,
	EXCLUIDO_POR_USU_ID INT,
    ID_ATIVO INT NOT NULL
)

CREATE TABLE ESTOQUE (
    ID INT PRIMARY KEY,
    ID_PRODUTO INT,
	NM_QUANTIDADE INT, 
	ID_ATIVO INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID)
)

CREATE TABLE VENDAS_PRODUTOS (
    ID INT PRIMARY KEY,
	ID_VENDA INT,
	ID_PRODUTO INT,
	VALOR NUMERIC (10,2),
	DESCONTO INT,
	VALOR_FINAL NUMERIC (10,2),
    DAT_CRIACAO DATETIME,
	DAT_ALTERACAO DATETIME,
	DAT_EXCLUSAO DATETIME,
	CRIADO_POR_USU_ID INT,
	ALTERADO_POR_USU_ID INT,
	EXCLUIDO_POR_USU_ID INT,
    ID_ATIVO INT NOT NULL,
	FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID),
	FOREIGN KEY (ID_VENDA) REFERENCES VENDAS (ID)
)
